# -*- coding: utf-8 -*-
"""Copy of Python And Cyber security.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uQTMpXXx-hz8NMUOHiPcUHfbMjGdFLtr
"""

import requests
#import os
from datetime import datetime
 
api_key = '016cb5ed243330161c1e10d51e0658de'
location = input("Enter the city name: ")
 
complete_api_link = "https://api.openweathermap.org/data/2.5/weather?q="+location+"&appid="+api_key
api_link = requests.get(complete_api_link)
api_data = api_link.json()
 
#create variable to store data
temp_city = ((api_data['main']['temp']) - 273.15)
weather_desc = api_data['weather'][0]['description']
hmdt = api_data['main']['humidity']
wind_spd = api_data['wind']['speed']
date_time = datetime.now().strftime("%d %b %Y | %I:%M:%S %p")
#print the data
print ("-------------------------------------------------------------")
print ("Weather Stats for - {}  || {}".format(location.upper(), date_time))
print ("-------------------------------------------------------------")
 
print ("Current temperature is: {:.2f} deg C".format(temp_city))
print ("Current weather desc  :",weather_desc)
print ("Current Humidity      :",hmdt, '%')
print ("Current wind speed    :",wind_spd ,'kmph')
 
print("====================================================")
 
 
#write the data for file name:location+date_time
txtlist = [temp_city,weather_desc,hmdt,wind_spd,date_time]
#using open() buit-in function to write to a text file
f=open(str(location)+str(date_time)+".txt" ,'w')  
f.write("------------------------------------------------------------- \n ")   
f.write("Weather Stats for - {}  || {}".format(location.upper(), date_time))
f.write("\n ------------------------------------------------------------- \n")
f.write("Current temperature is: {:.2f} deg C\n".format(txtlist[0]))
f.write("{},{} \n".format("Current weather desc  :" ,txtlist[1]))
f.write("{},{},{} \n".format("Current Humidity      :",txtlist[2],"%"))
f.write("{},{},{} \n".format("Current wind speed    :",txtlist[3],"kmph"))
f.write("------------------------------------------------------------- \n ")